language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

before_script:
  - yarn build
  - yarn angular-http-server --path dist/mele-ng -p 4200 &
script:
  - yarn cy:run -- --record
after_script:
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true
